language: csharp
dist: xenial
solution: TrustPayments.sln
git:
    quiet: true
install:
    - nuget restore TrustPayments.sln
    - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
    - msbuild /t:restore TrustPayments.sln
    - msbuild TrustPayments.sln /t:build /p:Configuration=Release
    - mono testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./src/TrustPayments.Test/bin/Release/net452/TrustPayments.Test.dll --inprocess
    - nuget push ./src/TrustPayments/bin/Release/TrustPayments.2.2.0.nupkg -Source nuget.org -ApiKey $NUGET_API_KEY_WALLEE  -Verbosity detailed -SkipDuplicate
